apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmargo
  namespace: argocd
spec: 
  project: spring-apps
  source:
    repoURL: https://github.com/bischs/DemoManifests.git
    targetRevision: HEAD
    path: demohelmchart
    helm:
      releaseName: helmargo
      valueFiles:
        - values.yaml
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-apps-dev
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apps
      kind: Secret
      jqPathExpressions:
        - '.data.color'
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/containers/image
      #jqPathExpressions:
        #- '.spec.containers[0].image'
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  #  automated:
  #    selfHeal: true
