apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmargo
  namespace: argocd
spec: 
  project: spring-apps
  source:
    repoURL: https://github.com/bischs/DemoManifests.git
    targetRevision: HEAD
    path: demohelmchart
    helm:
      releaseName: helmargo
      image.tag: 2.0.0
      valueFiles:
        - values.yaml
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-apps-dev
  #syncPolicy:
  #  automated:
  #    selfHeal: true
