apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-bluegreen
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/bischs/DemoManifests.git
    targetRevision: HEAD
    path: demorollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: rollouts
  #syncPolicy:
  #  automated:
  #    selfHeal: true
