# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: COLOR
          valueFrom:
            secretKeyRef:
              name: {{ .Values.colorSecretName }}
              key: color
        - name: COUNTRY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appConfigName }}
              key: country
        - name: CITY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.appConfigName }}
              key: city
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
