apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-app-hook-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
      - name: print-message
        image: alpine
        command: 
          - "/bin/sh"
          - "-c"
          - "email -s 'Application OK' simon.bisch@free.fr"
