apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-app-hook-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
      - name: print-message
        image: alpine
        command: 
          - "/bin/sh"
          - "-c"
          - "echo 'Application en cours de déploiement'"
