apiVersion: batch/v1
kind: Job
metadata:
  generateName: demo-app-hook-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: PrintMessage
        image: alpine
        command: 
          - "sh"
          - "echo"
        args: 
          - "L’application sera synchronisé avec un nouvel état désiré."